//! Formula/cartoon.rb is generated by scripts/update-formula.mjs; the
//! generator's self-test also checks that the committed formula is exactly
//! what it would produce, so a hand edit fails `cargo test`.
mod common;

use std::path::Path;
use std::process::Command;

fn root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn formula_generator_self_test() {
    if !common::have("node") {
        return;
    }
    let out = Command::new("node")
        .current_dir(root())
        .args(["scripts/update-formula.mjs", "--self-test"])
        .output()
        .unwrap();
    assert!(
        out.status.success(),
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
}

#[test]
fn formula_is_valid_ruby() {
    if !common::have("ruby") {
        return;
    }
    let out = Command::new("ruby")
        .current_dir(root())
        .args(["-c", "Formula/cartoon.rb"])
        .output()
        .unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
}

#[test]
fn formula_covers_every_unix_platform() {
    let rb = std::fs::read_to_string(root().join("Formula/cartoon.rb")).unwrap();
    for block in ["on_macos do", "on_linux do", "on_arm do", "on_intel do"] {
        assert!(rb.contains(block), "missing `{block}`");
    }
    assert_eq!(rb.matches("sha256 \"").count(), 4, "one checksum per platform");
    assert!(rb.contains("bin.install \"cartoon\""));
    assert!(rb.contains("cartoon --version"));
}
