# Generated by scripts/update-formula.mjs from the v0.6.0 SHA256SUMS.
# Do not edit by hand: release.yml regenerates it after every release.
class Cartoon < Formula
  desc "Compress test runner and CLI output into TOON for LLM agents"
  homepage "https://github.com/abhijitbansal/cartoon"
  version "0.6.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/abhijitbansal/cartoon/releases/download/v0.6.0/cartoon-aarch64-apple-darwin.tar.gz"
      sha256 "74056668d7a1e85ab5cf25927fb30d234533836fefd1567bbda97d98da4e92f7"
    end
    on_intel do
      url "https://github.com/abhijitbansal/cartoon/releases/download/v0.6.0/cartoon-x86_64-apple-darwin.tar.gz"
      sha256 "b98b7b67242126074d713dfc05c79a0fa48777530bf68ede198ca10f552b64ec"
    end
  end

  on_linux do
    # This release only published glibc builds (built on ubuntu-24.04,
    # glibc >= 2.39). Releases after 0.6.0 ship static musl tarballs.
    on_arm do
      url "https://github.com/abhijitbansal/cartoon/releases/download/v0.6.0/cartoon-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "9f33b5391ab9e0c194db1446a3ff02cd163aa81064583dc24663ec38a38ee3ee"
    end
    on_intel do
      url "https://github.com/abhijitbansal/cartoon/releases/download/v0.6.0/cartoon-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "d9bfeee7b7c8cd35228a0e89eaa84a8b8d8c1e2c34161c3c76cd8f3ac2fae86e"
    end
  end

  def install
    bin.install "cartoon"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cartoon --version")
  end
end
