# Generated by scripts/update-formula.mjs from the v0.7.0 SHA256SUMS.
# Do not edit by hand: release.yml regenerates it after every release.
class Cartoon < Formula
  desc "Compress test runner and CLI output into TOON for LLM agents"
  homepage "https://github.com/abhijitbansal/cartoon"
  version "0.7.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/abhijitbansal/cartoon/releases/download/v0.7.0/cartoon-aarch64-apple-darwin.tar.gz"
      sha256 "9ca2d16cd40de042e691cb2a2faf1695ee2e1ee5db2a7be746b3539d61510ef6"
    end
    on_intel do
      url "https://github.com/abhijitbansal/cartoon/releases/download/v0.7.0/cartoon-x86_64-apple-darwin.tar.gz"
      sha256 "ec6cf7c2c1f38443f0098ec329edd2b1c0a4816a2fb8df3466ea5a79aa9f6838"
    end
  end

  on_linux do
    # Static musl builds: no glibc version requirement.
    on_arm do
      url "https://github.com/abhijitbansal/cartoon/releases/download/v0.7.0/cartoon-aarch64-unknown-linux-musl.tar.gz"
      sha256 "63b222c7bf7805618df83375f73c1488e88f5210f09cabdfc77a10087eda534e"
    end
    on_intel do
      url "https://github.com/abhijitbansal/cartoon/releases/download/v0.7.0/cartoon-x86_64-unknown-linux-musl.tar.gz"
      sha256 "5c2e52c2100b337cbcd64ea604172b586c3168863c1deb5171a2e96be2688ba1"
    end
  end

  def install
    bin.install "cartoon"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cartoon --version")
  end
end
