// Regenerate the Homebrew formula (Formula/cartoon.rb) for a release from
// its SHA256SUMS. This repo doubles as the tap, so users run:
//
//   brew tap abhijitbansal/cartoon https://github.com/abhijitbansal/cartoon
//   brew install cartoon
//
// Usage:
//   node scripts/update-formula.mjs <version> <SHA256SUMS> [--out Formula/cartoon.rb]
//   node scripts/update-formula.mjs --self-test
//
// release.yml runs this after the GitHub release is published and opens a PR
// with the result. Linux prefers the static musl tarball and falls back to
// the glibc one (releases up to 0.6.0 published only gnu builds).
import fs from "node:fs";
import assert from "node:assert/strict";

const REPO = "https://github.com/abhijitbansal/cartoon";

// Formula slot -> release targets, most preferred first.
const SLOTS = {
  macos_arm: ["aarch64-apple-darwin"],
  macos_intel: ["x86_64-apple-darwin"],
  linux_arm: ["aarch64-unknown-linux-musl", "aarch64-unknown-linux-gnu"],
  linux_intel: ["x86_64-unknown-linux-musl", "x86_64-unknown-linux-gnu"],
};

/** Parse `sha256sum` output into { "cartoon-<target>.tar.gz": sha }. */
export function parseSums(text) {
  const sums = {};
  for (const line of text.split("\n")) {
    const m = line.trim().match(/^([0-9a-f]{64})\s+\*?(\S+)$/);
    if (m) sums[m[2]] = m[1];
  }
  return sums;
}

/** Pick the tarball for each slot; throws when a slot has none. */
export function pickAssets(sums) {
  const picked = {};
  for (const [slot, targets] of Object.entries(SLOTS)) {
    const target = targets.find((t) => sums[`cartoon-${t}.tar.gz`]);
    if (!target) throw new Error(`no tarball for ${slot} (want one of: ${targets.join(", ")})`);
    picked[slot] = { target, sha256: sums[`cartoon-${target}.tar.gz`] };
  }
  return picked;
}

export function renderFormula(version, sums) {
  if (!/^\d+\.\d+\.\d+([-.][0-9A-Za-z.-]+)?$/.test(version)) {
    throw new Error(`not a version: ${version}`);
  }
  const a = pickAssets(sums);
  const url = (slot) => `${REPO}/releases/download/v${version}/cartoon-${a[slot].target}.tar.gz`;
  const block = (slot, indent) =>
    `${indent}url "${url(slot)}"\n${indent}sha256 "${a[slot].sha256}"`;
  const gnu = ["linux_arm", "linux_intel"].some((s) => a[s].target.endsWith("-gnu"));
  const linuxNote = gnu
    ? "    # This release only published glibc builds (built on ubuntu-24.04,\n" +
      "    # glibc >= 2.39). Releases after 0.6.0 ship static musl tarballs.\n"
    : "    # Static musl builds: no glibc version requirement.\n";
  return `# Generated by scripts/update-formula.mjs from the v${version} SHA256SUMS.
# Do not edit by hand: release.yml regenerates it after every release.
class Cartoon < Formula
  desc "Compress test runner and CLI output into TOON for LLM agents"
  homepage "${REPO}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
${block("macos_arm", "      ")}
    end
    on_intel do
${block("macos_intel", "      ")}
    end
  end

  on_linux do
${linuxNote}    on_arm do
${block("linux_arm", "      ")}
    end
    on_intel do
${block("linux_intel", "      ")}
    end
  end

  def install
    bin.install "cartoon"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cartoon --version")
  end
end
`;
}

function selfTest() {
  const sha = (c) => c.repeat(64);
  const musl = [
    `${sha("a")}  cartoon-aarch64-apple-darwin.tar.gz`,
    `${sha("b")}  cartoon-x86_64-apple-darwin.tar.gz`,
    `${sha("c")}  cartoon-aarch64-unknown-linux-musl.tar.gz`,
    `${sha("d")} *cartoon-x86_64-unknown-linux-musl.tar.gz`,
    `${sha("e")}  cartoon-x86_64-pc-windows-msvc.tar.gz`,
    "",
  ].join("\n");

  // Every slot gets its own URL and checksum; Windows is ignored.
  const rb = renderFormula("0.7.0", parseSums(musl));
  assert.match(rb, /version "0\.7\.0"/);
  for (const [t, c] of [
    ["aarch64-apple-darwin", "a"],
    ["x86_64-apple-darwin", "b"],
    ["aarch64-unknown-linux-musl", "c"],
    ["x86_64-unknown-linux-musl", "d"],
  ]) {
    assert.ok(
      rb.includes(`download/v0.7.0/cartoon-${t}.tar.gz"\n      sha256 "${sha(c)}"`),
      `${t} url/sha pair`,
    );
  }
  assert.ok(!rb.includes("windows"));
  assert.ok(!rb.includes("glibc >= 2.39"));

  // musl wins over gnu when both exist; gnu is the fallback.
  const both = parseSums(musl + `${sha("f")}  cartoon-x86_64-unknown-linux-gnu.tar.gz\n`);
  assert.equal(pickAssets(both).linux_intel.target, "x86_64-unknown-linux-musl");
  const gnuOnly = musl.replace(/linux-musl/g, "linux-gnu");
  const rbGnu = renderFormula("0.6.0", parseSums(gnuOnly));
  assert.ok(rbGnu.includes("cartoon-x86_64-unknown-linux-gnu.tar.gz"));
  assert.ok(rbGnu.includes("glibc >= 2.39"));

  // A missing platform or a bad version is an error, never a broken formula.
  assert.throws(() => renderFormula("0.7.0", parseSums(musl.split("\n").slice(1).join("\n"))), /macos_arm/);
  assert.throws(() => renderFormula("v0.7.0", parseSums(musl)), /not a version/);

  // The committed formula is what the generator produces for its own inputs.
  const committed = fs.existsSync("Formula/cartoon.rb") && fs.readFileSync("Formula/cartoon.rb", "utf8");
  if (committed) {
    const v = committed.match(/^\s*version "([^"]+)"/m)[1];
    const sums = {};
    for (const m of committed.matchAll(/cartoon-([\w-]+)\.tar\.gz"\n\s*sha256 "([0-9a-f]{64})"/g)) {
      sums[`cartoon-${m[1]}.tar.gz`] = m[2];
    }
    assert.equal(renderFormula(v, sums), committed, "Formula/cartoon.rb was edited by hand");
  }
  console.log("update-formula: self-test ok");
}

function main(argv) {
  if (argv.includes("--self-test")) return selfTest();
  const outIdx = argv.indexOf("--out");
  const out = outIdx >= 0 ? argv[outIdx + 1] : "Formula/cartoon.rb";
  const pos = outIdx >= 0 ? argv.filter((_, i) => i !== outIdx && i !== outIdx + 1) : argv;
  if (pos.length !== 2) {
    console.error("usage: update-formula.mjs <version> <SHA256SUMS> [--out FILE] | --self-test");
    process.exit(2);
  }
  const version = pos[0].replace(/^v/, "");
  const rb = renderFormula(version, parseSums(fs.readFileSync(pos[1], "utf8")));
  fs.mkdirSync(out.replace(/\/[^/]*$/, "") || ".", { recursive: true });
  fs.writeFileSync(out, rb);
  console.log(`update-formula: wrote ${out} for v${version}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  try {
    main(process.argv.slice(2));
  } catch (e) {
    console.error(`update-formula: ${e.message}`);
    process.exit(1);
  }
}
