//! `cartoon shim` — shell-function wrappers that transparently run noisy
//! dev-loop tools under cartoon. This is the agent-agnostic fallback for
//! tools without a PreToolUse hook (and a belt-and-suspenders layer
//! alongside hooks): a shell function shadows the bare tool name and
//! re-invokes it through `cartoon`, so wrapping happens without the agent
//! choosing to. Functions take precedence over PATH and over venv-local
//! binaries, so an activated venv's `pytest` is still caught.
//!
//! Reuses the hook's allowlist constants (`hook::ALWAYS` etc.) as the single
//! source of truth. Coverage is close but not identical to the hook: the
//! shim has no function for `python -m pytest` or `xcodebuild` actions, and
//! skips tool names that aren't valid POSIX function names (e.g.
//! `pre-commit`) — those stay covered by the hook.
//!
//! Limitations vs the hook: a shell function sees only its own argv, not the
//! surrounding pipe/redirection, so it can't refuse `pytest | grep x` the
//! way the hook does — keep shims to the test/build tools the agent runs
//! bare. Path-invoked binaries (`./gradlew`, `./node_modules/.bin/jest`)
//! bypass function lookup entirely. Disable per-shell with `CARTOON_NO_SHIM=1`.
use crate::hook::{ALWAYS, RUNNERS, SUBCOMMAND};
use anyhow::{bail, Result};

pub fn run(args: &[String]) -> Result<i32> {
    match args.first().map(String::as_str) {
        Some("print") => {
            print!("{}", script());
            Ok(0)
        }
        Some("install") => install(),
        Some("uninstall") => uninstall(),
        Some("status") => status(),
        Some("path") => {
            println!("{}", shims_path()?.display());
            Ok(0)
        }
        _ => bail!("usage: cartoon shim (print | install | uninstall | status | path)"),
    }
}

/// The sourceable shell script: one function per allowlisted tool.
pub fn script() -> String {
    let mut s = String::new();
    // Header + shared dispatcher: run the tool under cartoon, or bare when
    // disabled or cartoon is missing. `command` bypasses these functions, so
    // the child never re-enters the shim (cartoon also execs the binary).
    s.push_str(
        r#"# cartoon shim — transparently wrap noisy dev tools.
# Generated by `cartoon shim`. Disable per-shell with CARTOON_NO_SHIM=1.
__cartoon_run() {
  if [ -n "${CARTOON_NO_SHIM:-}" ] || ! command -v cartoon >/dev/null 2>&1; then
    command "$@"
  else
    cartoon "$@"
  fi
}
"#,
    );
    // Always-noisy tools: wrap regardless of args. Skip names that aren't
    // valid POSIX function names (e.g. `pre-commit`) — sh/dash reject the
    // definition with "Bad function name" and abort the WHOLE sourced file,
    // killing every shim. Such tools are still covered by the hook.
    for t in ALWAYS.iter().filter(|t| portable_fn_name(t)) {
        s.push_str(&format!("{t}() {{ __cartoon_run {t} \"$@\"; }}\n"));
    }
    // Subcommand-gated tools: wrap only the read-mostly subcommands, mirroring
    // the hook so `cargo publish` / `npm install` still run bare.
    for (tool, subs) in SUBCOMMAND.iter().filter(|(t, _)| portable_fn_name(t)) {
        let pat = subs.join("|");
        s.push_str(&format!(
            "{tool}() {{ case \"${{1:-}}\" in {pat}) __cartoon_run {tool} \"$@\" ;; *) command {tool} \"$@\" ;; esac; }}\n"
        ));
    }
    // Runner prefixes (npx/bunx/pnpx): wrap when the target is a noisy tool.
    let targets = ALWAYS.join("|");
    for r in RUNNERS {
        s.push_str(&format!(
            "{r}() {{ case \"${{1:-}}\" in {targets}) __cartoon_run {r} \"$@\" ;; *) command {r} \"$@\" ;; esac; }}\n"
        ));
    }
    s
}

/// A shell function name that POSIX sh/dash will accept (`[A-Za-z0-9_]`).
/// Hyphenated names like `pre-commit` are bash/zsh-only and break a sourced
/// file under sh, so we don't define functions for them.
fn portable_fn_name(name: &str) -> bool {
    !name.is_empty() && name.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'_')
}

fn shims_path() -> Result<std::path::PathBuf> {
    crate::paths::shims_file().ok_or_else(|| anyhow::anyhow!("cannot resolve config directory"))
}

fn install() -> Result<i32> {
    let path = shims_path()?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, script())?;
    let p = path.display();
    println!(
        "cartoon shims written to {p}\n\
         \n\
         Activate them:\n\
         \n  # interactive shells — add to ~/.bashrc or ~/.zshrc:\n\
         \n      [ -f {p} ] && . {p}\n\
         \n  # non-interactive shells (what most agents spawn) — set in the\n\
         \n  # environment / devcontainer / CI so `bash -c` picks it up:\n\
         \n      export BASH_ENV={p}\n\
         \n\
         Disable anytime with CARTOON_NO_SHIM=1. Re-run after upgrading cartoon."
    );
    Ok(0)
}

fn uninstall() -> Result<i32> {
    let path = shims_path()?;
    if path.exists() {
        std::fs::remove_file(&path)?;
        println!(
            "removed {}\nAlso drop any `. {}` / BASH_ENV line you added.",
            path.display(),
            path.display()
        );
    } else {
        println!("nothing to remove: {} not found", path.display());
    }
    Ok(0)
}

fn status() -> Result<i32> {
    let path = shims_path()?;
    println!(
        "{}: {}",
        path.display(),
        if path.exists() {
            "written (activation depends on your shell rc / BASH_ENV)"
        } else {
            "not written"
        }
    );
    Ok(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn always_tools_wrap_unconditionally() {
        let s = script();
        assert!(s.contains("pytest() { __cartoon_run pytest \"$@\"; }"));
        assert!(s.contains("eslint() { __cartoon_run eslint \"$@\"; }"));
    }

    #[test]
    fn subcommand_tools_are_gated() {
        let s = script();
        // cargo only wraps the read-mostly subcommands, else runs bare.
        assert!(s.contains("cargo() { case \"${1:-}\" in build|test|check|clippy|doc|nextest)"));
        assert!(s.contains("*) command cargo \"$@\" ;;"));
    }

    #[test]
    fn runners_wrap_only_noisy_targets() {
        let s = script();
        assert!(s.contains("npx() { case \"${1:-}\" in pytest|jest|vitest"));
    }

    #[test]
    fn has_disable_escape_hatch() {
        assert!(script().contains("CARTOON_NO_SHIM"));
    }

    #[test]
    fn skips_non_portable_function_names() {
        // `pre-commit` would be a "Bad function name" in sh/dash and abort
        // the whole sourced file, so no hyphenated function is defined.
        let s = script();
        assert!(!s.contains("pre-commit() {"), "hyphenated fn def leaked");
        // Every emitted `name() {` definition uses a portable name.
        for line in s.lines() {
            if let Some(name) = line.split("()").next().filter(|_| line.contains("() {")) {
                let name = name.trim();
                assert!(
                    portable_fn_name(name),
                    "non-portable function name emitted: {name:?}"
                );
            }
        }
    }
}
